API
java-park-mail-ru/ananymous-02-2017 pull request #2
Opened 2017-03-08 11:09 UTC by Chocco-Crokko

2017-03-12 18:57 UTC, KSolovyev requested changes

2017-03-12 18:57 UTC, KSolovyev commented on src/main/java/application/db/Database.java
> +public interface Database {
Если по смыслу это интерфейс работы с пользователем, то давайте так его и назовем

2017-03-12 18:57 UTC, KSolovyev commented on src/main/java/application/models/User.java
> +public class User extends UserInfo {
вот здесь наследование ошибочно. Пользователь не есть подкласс UserInfo. Он в себя его включает. Подумайте, что здесь можно сделать

2017-03-12 18:57 UTC, KSolovyev commented on src/main/java/application/db/Database.java
> +public interface Database {
Точнее у вас этот класс, как UserDAO

2017-03-12 18:57 UTC, KSolovyev commented on src/main/java/application/utils/Validator.java
> +            return "Invalid login: " + user.getLogin();
Когда сообщаете пользователю, что он ошибся, нужно еще сказать, что ему сделать. Что-то вроде "Логин должен содержать латинские буквы или цифры и быть от 3 до 20 символов"

2017-03-12 18:57 UTC, KSolovyev commented on src/main/resources/application.properties
> +logging.level.root = trace
это у вас и на бою тогда trace будет. На бою должен быть максимум info

2017-03-12 18:57 UTC, KSolovyev commented on pom.xml
> +        <!--<spring.version>1.5.1.RELEASE</spring.version>-->
убираем

2017-03-12 18:57 UTC, KSolovyev commented on pom.xml
> +        <version>1.5.1.RELEASE</version>
1.5.2.RELEASE вышел

2017-03-12 19:08 UTC, Chocco-Crokko commented on src/main/java/application/utils/Validator.java
> +            return "Invalid login: " + user.getLogin();
По идее, все основные проверки должны быть сделаны на фронтэнде, нет? И там сообщать про все требования. Я делал проверки от "плохих" пользователей, которые как-то обошли фронт-часть

2017-03-12 19:29 UTC, KSolovyev commented on src/main/java/application/utils/Validator.java
> +            return "Invalid login: " + user.getLogin();
ок, пусть будет так. Но вообще API делается как изолированная система. Подробные ошибки могут помочь вам, например, при отладке. Или если будут внешние клиенты

2017-03-20 18:58 UTC, KSolovyev commented
Версия стабильна, еще чего-нибудь хотите добавить?

2017-03-20 19:34 UTC, Chocco-Crokko commented
К следующему РК разве что. Пока нет)

2017-03-20 20:07 UTC, merged