RK3, 4
java-park-mail-ru/ananymous-02-2017 pull request #7
Opened 2017-05-25 14:50 UTC by vladpereskokov

2017-06-01 10:54 UTC, Chocco-Crokko commented
@KSolovyev 
Пинг

2017-06-01 20:46 UTC, KSolovyev requested changes

2017-06-01 20:46 UTC, KSolovyev commented on src/main/java/application/mechanics/MechanicsExecutor.java
> +    private final ThreadFactory threadFactory = new ThreadFactory(){
а почему не Executors.newFixedThreadPoolExecutor() ?

2017-06-01 20:46 UTC, KSolovyev commented on src/main/java/application/mechanics/MechanicsExecutor.java
> +            if (gameMechanics[i].getSessionsNum() < currentMin) {
такая балансировка не айс. Будет гонка между создающимися играми и количеством ожидающий игроков. В итоге может "проскочить" лишний пользователь, который на этой механике и повиснет

2017-06-01 20:46 UTC, KSolovyev commented on src/main/java/application/mechanics/MechanicsExecutor.java
> +            if (gameMechanic.isPlaying(forUser)) {
вот тут будет гонка между isPlaying и addClientSnapshot

2017-06-01 20:46 UTC, KSolovyev commented on src/main/java/application/mechanics/base/Map.java
> +    public static final int[][] MAP = {
Вот эту штуку хорошо бы в ресурсы было вынести. Но уже не парьтесь, не надо править

2017-06-01 20:46 UTC, KSolovyev commented on src/main/java/application/mechanics/base/geometry/Coordinates.java
> +//        this.x = x + Map.m * Config.BLOCK_SIZE + Config.BLOCK_SIZE / 2;
надо почистить закомментированный код. Пробегитесь по проекту

2017-06-01 20:57 UTC, KSolovyev requested changes

2017-06-01 20:57 UTC, KSolovyev commented on src/main/java/application/mechanics/internal/GameSessionService.java
> +                remotePointService.cutDownConnection(player.getId(), CloseStatus.SERVER_ERROR);
Вроде у вас эта функция зовется и при нормальном завершении игры. Почему всегда SERVER_ERROR?

2017-06-01 20:57 UTC, KSolovyev commented on src/main/java/application/mechanics/handlers/DisconnectUserHandler.java
> +        mechanicExecutor.removeUser(forUser);
вот тут гонка будет

2017-06-01 20:57 UTC, KSolovyev commented on src/main/java/application/mechanics/handlers/DisconnectUserHandler.java
> +        mechanicExecutor.removeUser(forUser);
надо тоже через таски сделать

2017-06-01 20:57 UTC, KSolovyev commented on src/main/java/application/mechanics/GameMechanics.java
> +    public GameSession getSessionForUser(long user) {
не используется

2017-06-01 20:57 UTC, KSolovyev commented on src/main/java/application/mechanics/handlers/MyHandler.java
> +public class MyHandler extends MessageHandler<String> {
удалить

2017-06-02 13:12 UTC, Chocco-Crokko commented on src/main/java/application/mechanics/MechanicsExecutor.java
> +    private final ThreadFactory threadFactory = new ThreadFactory(){
Что это?
У меня есть только `Executors.newFixedThreadPool`, который и использовался

2017-06-02 13:33 UTC, KSolovyev commented on src/main/java/application/mechanics/MechanicsExecutor.java
> +    private final ThreadFactory threadFactory = new ThreadFactory(){
да, забыл удалить коммент

2017-06-02 19:33 UTC, KSolovyev commented
а можно ссылку на фронт?

2017-06-02 19:52 UTC, Chocco-Crokko commented
Да, конечно.
Если нужна игра, то вот: soul-hunting.ru
Если нужен репозиторий, то Влад приглашение кинет, он у нас приватный.

После защиты ещё можно будет получать баллы? А то ПР не закрыт будет, получается

2017-06-02 20:21 UTC, KSolovyev commented
Завтра обсудим

2017-09-18 10:18 UTC, merged